name: Unit Test Check

on: [push, pull_request, workflow_dispatch]

jobs:
  unittest-pytest:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build
          pip install .[dev]
      - name: Test with pytest
        run: |
          pytest
