name: Unit Test Check

on: [pull_request, workflow_dispatch]

jobs:
  unittest-pytest:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Build Project
        run: python -m build
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/vsmp_epd.egg-info/requires.txt
